# Generated by Django 2.1.4 on 2019-02-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0003_auto_20190201_2226'),
        ('vcssa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='union_name',
            field=models.CharField(blank=True, default='', help_text='Enter your union name', max_length=500, null=True),
        ),
    ]
