# Generated by Django 2.1.4 on 2019-01-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('vcssa', '0002_auto_20190121_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitypage',
            old_name='detail',
            new_name='body',
        ),
        migrations.AddField(
            model_name='activitypage',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
