# Generated by Django 2.1.5 on 2019-03-11 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0002_auto_20190310_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='application_form_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish Date'),
        ),
    ]
