# Generated by Django 2.1.4 on 2019-02-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190202_1832'),
        ('vcssa', '0003_auto_20190202_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityindexpage',
            name='theme_background',
            field=models.ForeignKey(limit_choices_to={'type': 'ACTIVITY_INDEX_BACKGROUND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_index_background_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='activityindexpage',
            name='theme_catalog',
            field=models.ForeignKey(limit_choices_to={'type': 'ACTIVITY_INDEX_CATALOG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_index_catalog_theme', to='home.Theme'),
        ),
    ]
