# Generated by Django 2.1.4 on 2019-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0003_auto_20190121_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='intro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
