# Generated by Django 2.1.4 on 2019-02-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190202_1845'),
        ('vcssa', '0004_auto_20190202_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='theme',
            field=models.ForeignKey(limit_choices_to={'type': 'ACTIVITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_theme', to='home.Theme'),
        ),
    ]
