# Generated by Django 2.1.5 on 2019-03-13 00:36

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0004_subunionhomepage_page_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='activity_times',
            field=wagtail.core.fields.StreamField([('time_slot', wagtail.core.blocks.StructBlock([('starting_time', wagtail.core.blocks.DateTimeBlock(format='%Y-%m-%d %H:%M', required=False)), ('ending_time', wagtail.core.blocks.DateTimeBlock(format='%Y-%m-%d %H:%M', required=False)), ('label', wagtail.core.blocks.CharBlock(default='', max_length=200, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='timezone',
            field=models.CharField(choices=[('Melbourne', 'Melbourne'), ('Beijing', 'Beijing')], default='mel', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='venues',
            field=wagtail.core.fields.StreamField([('venue', wagtail.core.blocks.CharBlock(max_length=500, required=False))], blank=True, default='', null=True),
        ),
    ]
