# Generated by Django 2.1.4 on 2019-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0004_auto_20190121_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspage',
            name='intro_image',
        ),
    ]
