# Generated by Django 2.1.4 on 2019-02-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190202_1854'),
        ('vcssa', '0005_activitypage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='theme',
            field=models.ForeignKey(limit_choices_to={'type': 'CONTACT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_theme', to='home.Theme'),
        ),
    ]
