# Generated by Django 2.1.5 on 2019-03-13 01:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0005_auto_20190313_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypage',
            name='activity_times',
        ),
        migrations.RemoveField(
            model_name='activitypage',
            name='venues',
        ),
        migrations.AddField(
            model_name='activitypage',
            name='activity_info',
            field=wagtail.core.fields.StreamField([('activity_info', wagtail.core.blocks.StructBlock([('starting_time', wagtail.core.blocks.DateTimeBlock(format='%Y-%m-%d %H:%M', required=False)), ('ending_time', wagtail.core.blocks.DateTimeBlock(format='%Y-%m-%d %H:%M', required=False)), ('venue', wagtail.core.blocks.CharBlock(max_length=500, required=False)), ('label', wagtail.core.blocks.CharBlock(default='', max_length=200, required=False))]))], blank=True, null=True),
        ),
    ]
