# Generated by Django 2.1.4 on 2019-02-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190202_1913'),
        ('vcssa', '0006_contactuspage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindexpage',
            name='theme_background',
            field=models.ForeignKey(limit_choices_to={'type': 'NEWS_INDEX_BACKGROUND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_index_background_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='theme_content',
            field=models.ForeignKey(limit_choices_to={'type': 'NEWS_INDEX_CONTENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_index_content_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='theme',
            field=models.ForeignKey(limit_choices_to={'type': 'NEWS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_page_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='newstagindexpage',
            name='theme',
            field=models.ForeignKey(limit_choices_to={'type': 'NEWS_TAGS_INDEX'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_tag_index_theme', to='home.Theme'),
        ),
    ]
