# Generated by Django 2.1.4 on 2019-02-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190207_1737'),
        ('vcssa', '0007_auto_20190202_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunionindexpage',
            name='theme_background',
            field=models.ForeignKey(limit_choices_to={'type': 'SUBUNION_INDEX_BACKGROUND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_index_background_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='subunionindexpage',
            name='theme_content',
            field=models.ForeignKey(limit_choices_to={'type': 'SUBUNION_INDEX_CONTENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_index_content_theme', to='home.Theme'),
        ),
    ]
