# Generated by Django 2.1.4 on 2019-02-01 01:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('welcome', models.CharField(default='Welcome to VCSSA!', max_length=200)),
                ('index_pages', wagtail.core.fields.StreamField([('index_page', wagtail.core.blocks.PageChooserBlock(['vcssa.NewsPage', 'vcssa.ActivityPage'], null=True, required=False))], blank=True, null=True)),
                ('background_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('logo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('HOME_BACKGROUND', 'Home Background'), ('HOME_SLIDE', 'Home Slide'), ('HOME_NEWS', 'Home News')], default='HOME_BACKGROUND', max_length=255, null=True)),
                ('template_path', models.CharField(blank=True, help_text='Enter full template path with name, or leave it blank to use default template path', max_length=255, null=True)),
                ('preview_photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_background',
            field=models.ForeignKey(limit_choices_to={'type': 'HOME_BACKGROUND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_news',
            field=models.ForeignKey(limit_choices_to={'type': 'HOME_NEWS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_theme', to='home.Theme'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_slide',
            field=models.ForeignKey(limit_choices_to={'type': 'HOME_SLIDE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_theme', to='home.Theme'),
        ),
    ]
