# Generated by Django 2.1.4 on 2019-02-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default='The introduction of your union', help_text='Introduce your union here', max_length=255),
        ),
    ]
