# Generated by Django 2.1.4 on 2019-01-20 23:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='news_pages',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='related_news_page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='index_pages',
            field=wagtail.core.fields.StreamField([('index_page', wagtail.core.blocks.PageChooserBlock(['vcssa.NewsPage', 'vcssa.ActivityPage'], null=True))], blank=True, null=True),
        ),
    ]
