# Generated by Django 2.1.5 on 2019-03-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('welcome', models.CharField(default='This is the root page, do not use me as home!', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='theme', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='preview_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='template_path',
            field=models.CharField(default='/Users/jiapeng/vcssaweb/VCSSAWebProject', help_text='Enter full template path with name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(choices=[('HOME_BACKGROUND', 'Home Background'), ('HOME_SLIDE', 'Home Slide'), ('HOME_NEWS', 'Home News'), ('ABOUT', 'About'), ('ACTIVITY_INDEX_BACKGROUND', 'Activity Index Background'), ('ACTIVITY_INDEX_CATALOG', 'Activity Index Catalog'), ('ACTIVITY', 'Activity'), ('CONTACT', 'Contact Us'), ('NEWS_TAGS_INDEX', 'News Tag'), ('NEWS', 'News'), ('NEWS_INDEX_BACKGROUND', 'News Index Background'), ('NEWS_INDEX_CONTENT', 'News Index Content'), ('SUBUNION_INDEX_BACKGROUND', 'Subunion Index Background'), ('SUBUNION_INDEX_CONTENT', 'Subunion Index Content')], default='HOME_BACKGROUND', max_length=255),
        ),
    ]
