# Generated by Django 2.1.4 on 2019-02-01 11:26

from django.db import migrations, models
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='posters',
            field=wagtail.core.fields.StreamField([('posters', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='template_path',
            field=models.CharField(blank=True, help_text='Enter full template path with name.', max_length=255, null=True),
        ),
    ]
