# Generated by Django 2.1.5 on 2019-03-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190310_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_full_title',
            field=models.CharField(blank=True, default='Victoria Chinese Student and Scholar Association', max_length=500, null=True),
        ),
    ]
