# Generated by Django 2.1.4 on 2019-02-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190201_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(blank=True, choices=[('HOME_BACKGROUND', 'Home Background'), ('HOME_SLIDE', 'Home Slide'), ('HOME_NEWS', 'Home News'), ('ABOUT', 'About')], default='HOME_BACKGROUND', max_length=255, null=True),
        ),
    ]
