# Generated by Django 2.1.4 on 2019-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190202_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(blank=True, choices=[('HOME_BACKGROUND', 'Home Background'), ('HOME_SLIDE', 'Home Slide'), ('HOME_NEWS', 'Home News'), ('ABOUT', 'About'), ('ACTIVITY_INDEX_BACKGROUND', 'Activity Index Background'), ('ACTIVITY_INDEX_CATALOG', 'Activity Index Catalog'), ('ACTIVITY', 'Activity')], default='HOME_BACKGROUND', max_length=255, null=True),
        ),
    ]
