# Generated by Django 2.1.4 on 2019-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190202_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(blank=True, choices=[('HOME_BACKGROUND', 'Home Background'), ('HOME_SLIDE', 'Home Slide'), ('HOME_NEWS', 'Home News'), ('ABOUT', 'About'), ('ACTIVITY_INDEX_BACKGROUND', 'Activity Index Background'), ('ACTIVITY_INDEX_CATALOG', 'Activity Index Catalog'), ('ACTIVITY', 'Activity'), ('CONTACT', 'Contact Us'), ('NEWS_TAGS_INDEX', 'News Tag'), ('NEWS', 'News'), ('NEWS_INDEX_BACKGROUND', 'News Index Background'), ('NEWS_INDEX_CONTENT', 'News Index Content')], default='HOME_BACKGROUND', max_length=255, null=True),
        ),
    ]
