# Generated by Django 2.1.4 on 2019-02-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190207_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='theme', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='template_path',
            field=models.CharField(default='C:\\Users\\dlt\\Documents\\Work\\VCSSA\\Backup\\Load Theme\\vcssaweb-jiapeng', help_text='Enter full template path with name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(choices=[('HOME_BACKGROUND', 'Home Background'), ('HOME_SLIDE', 'Home Slide'), ('HOME_NEWS', 'Home News'), ('ABOUT', 'About'), ('ACTIVITY_INDEX_BACKGROUND', 'Activity Index Background'), ('ACTIVITY_INDEX_CATALOG', 'Activity Index Catalog'), ('ACTIVITY', 'Activity'), ('CONTACT', 'Contact Us'), ('NEWS_TAGS_INDEX', 'News Tag'), ('NEWS', 'News'), ('NEWS_INDEX_BACKGROUND', 'News Index Background'), ('NEWS_INDEX_CONTENT', 'News Index Content'), ('SUBUNION_INDEX_BACKGROUND', 'Subunion Index Background'), ('SUBUNION_INDEX_CONTENT', 'Subunion Index Content')], default='HOME_BACKGROUND', max_length=255),
        ),
    ]
