# Generated by Django 2.1.4 on 2019-01-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_related_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='related_page',
            new_name='related_news_page',
        ),
    ]
