# Generated by Django 2.1.4 on 2019-01-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0003_auto_20190111_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='repeated_item_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
