# Generated by Django 2.1.4 on 2019-01-17 12:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190117_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_pages',
            field=wagtail.core.fields.StreamField([('news', wagtail.core.blocks.PageChooserBlock('NewsPage', null=True))], null=True),
        ),
    ]
