# Generated by Django 2.1.4 on 2019-01-17 12:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_news_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news_pages',
            field=wagtail.core.fields.StreamField([('news', wagtail.core.blocks.PageChooserBlock('vcssa.NewsPage', null=True))], null=True),
        ),
    ]
