# Generated by Django 2.1.4 on 2019-01-17 13:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190117_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news_pages',
            field=wagtail.core.fields.StreamField([('news', wagtail.core.blocks.PageChooserBlock('vcssa.NewsPage', null=True))], blank=True, null=True),
        ),
    ]
