# Generated by Django 2.1.5 on 2019-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'The email has already been registered.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
