# Generated by Django 2.1.5 on 2019-03-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190210_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subunions',
        ),
        migrations.AddField(
            model_name='user',
            name='subunions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Subunions'),
        ),
    ]
