# Generated by Django 2.1.4 on 2019-01-19 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0003_auto_20190119_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunionuser',
            name='group',
        ),
        migrations.AddField(
            model_name='subunionuser',
            name='group',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='subunionuser',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='Editor'), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
