# Generated by Django 2.1.5 on 2019-03-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0003_auto_20190311_1422'),
        ('users', '0004_auto_20190310_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_activities',
            field=models.ManyToManyField(to='vcssa.ActivityPage'),
        ),
    ]
