# Generated by Django 2.1.4 on 2019-01-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190119_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunionuser',
            name='group',
            field=models.ManyToManyField(limit_choices_to=models.Q(groups__name='Editor'), to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='subunionuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
