# Generated by Django 2.1.4 on 2019-01-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190120_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunionuser',
            name='group',
            field=models.ManyToManyField(limit_choices_to=models.Q(name='Editor'), to='auth.Group'),
        ),
    ]
