# Generated by Django 2.1.4 on 2019-01-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190120_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunionuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subunionuser',
            name='site',
        ),
        migrations.RemoveField(
            model_name='subunionuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(limit_choices_to=models.Q(name='editor'), to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='SubunionUser',
        ),
    ]
