# Generated by Django 2.1.4 on 2019-01-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subunionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunionuser',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
