# Generated by Django 2.1.4 on 2019-01-07 02:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='vcssa.AboutPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubUnionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(blank=True, max_length=500)),
                ('subunion_1_name', models.CharField(default='Deakin University', max_length=30, verbose_name='subunion_1_name')),
                ('subunion_1_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_1_intro')),
                ('subunion_2_name', models.CharField(default='La Trobe University', max_length=30, verbose_name='subunion_2_name')),
                ('subunion_2_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_2_intro')),
                ('subunion_3_name', models.CharField(default='Monash University', max_length=30, verbose_name='subunion_3_name')),
                ('subunion_3_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_3_intro')),
                ('subunion_4_name', models.CharField(default='RMIT University', max_length=30, verbose_name='subunion_4_name')),
                ('subunion_4_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_4_intro')),
                ('subunion_5_name', models.CharField(default='Swinburne University', max_length=30, verbose_name='subunion_5_name')),
                ('subunion_5_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_5_intro')),
                ('subunion_6_name', models.CharField(default='The University of Melbourne', max_length=30, verbose_name='subunion_6_name')),
                ('subunion_6_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_6_intro')),
                ('subunion_7_name', models.CharField(default='University of Tasmania', max_length=30, verbose_name='subunion_7_name')),
                ('subunion_7_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_7_intro')),
                ('subunion_8_name', models.CharField(default='Victoria University', max_length=30, verbose_name='subunion_8_name')),
                ('subunion_8_intro', models.CharField(default='Please add some intro to your union here', max_length=200, verbose_name='subunion_8_intro')),
                ('subunion_1_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_1_logo', to='wagtailimages.Image')),
                ('subunion_2_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_2_logo', to='wagtailimages.Image')),
                ('subunion_3_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_3_logo', to='wagtailimages.Image')),
                ('subunion_4_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_4_logo', to='wagtailimages.Image')),
                ('subunion_5_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_5_logo', to='wagtailimages.Image')),
                ('subunion_6_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_6_logo', to='wagtailimages.Image')),
                ('subunion_7_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_7_logo', to='wagtailimages.Image')),
                ('subunion_8_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunion_8_logo', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubUnionIndexPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_union_images', to='vcssa.SubUnionIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
