# Generated by Django 2.1.4 on 2019-01-16 23:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuspage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, default='Please contact us through our WeChat, or leave a message'),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='Thank you for contacting us! We will get back to you soon.'),
        ),
    ]
