# Generated by Django 2.1.4 on 2019-01-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0002_auto_20190117_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityindexpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activityindexpagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='ActivityIndexPageGalleryImage',
        ),
    ]
