# Generated by Django 2.1.4 on 2019-01-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('vcssa', '0003_activityindexbackgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityindexpage',
            name='bk_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
