# Generated by Django 2.1.4 on 2019-01-17 01:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0003_auto_20190117_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='detail',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
