# Generated by Django 2.1.4 on 2019-01-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0004_activitypage_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspage',
            name='email_password',
        ),
    ]
