# Generated by Django 2.1.4 on 2019-01-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0004_activityindexpage_bk_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityindexbackgroundimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activityindexbackgroundimage',
            name='page',
        ),
        migrations.RenameField(
            model_name='activityindexpage',
            old_name='bk_image',
            new_name='background_image',
        ),
        migrations.DeleteModel(
            name='ActivityIndexBackgroundImage',
        ),
    ]
