# Generated by Django 2.1.4 on 2019-01-17 03:03

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0005_remove_contactuspage_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(help_text='Configure your form here', on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='vcssa.ContactUsPage'),
        ),
    ]
