# Generated by Django 2.1.4 on 2019-01-17 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0008_newspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 4, 18, 24, 156730, tzinfo=utc), verbose_name='Post date'),
        ),
    ]
