# Generated by Django 2.1.4 on 2019-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0009_auto_20190117_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
