# Generated by Django 2.1.4 on 2019-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0012_auto_20190117_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
