# Generated by Django 2.1.4 on 2019-01-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('vcssa', '0013_auto_20190117_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
