# Generated by Django 2.1.4 on 2019-01-17 13:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcssa', '0014_newspage_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
